spring:
  application:
    name: auth-service

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "${CLIENT_ID}"
            client-secret: "${CLIENT_SECRET}"
            scope:
              - read:user
            redirect-uri: "${OAUTH2_BASE_URL:}/login/oauth2/code/github"
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/auth_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
server:
  port: 9900


com:
  llmreview:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      issuer: ${JWT_ISSUER}
      audience: ${JWT_AUDIENCE}
      expirationTime: 3600000
logging:
  level:
    com.llmreview.auth: DEBUG