spring:
  application:
    name: backend-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/application_db}
      username: ${MONGODB_USER:application_user}
      password: ${MONGODB_PASSWORD:application_password}
      authentication-database: ${MONGODB_AUTH_DB:admin}
      repositories:
        type: reactive

  webflux:
    hiddenmethod:
      filter:
        enabled: true

  devtools:
    restart:
      enabled: true

logging:
  level:
    web: error
    com.llmreview.api: error

---
spring:
  profiles:
    active: dev