server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: review-web
              uri: http://localhost:8082
              predicates:
                - Path=/v1/api/**
com:
  llmreview:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      issuer: ${JWT_ISSUER}

logging:
  level:
    com.llmreview: debug