services:
  application-db:
    image: mongo:latest
    container_name: application-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=application_user
      - MONGO_INITDB_ROOT_PASSWORD=application_password
      - MONGO_INITDB_DATABASE=application_db
      - MONGO_INITDB_AUTHENTICATION_DATABASE=admin
    ports:
      - "27017:27017"
